clickadmin/experiments/models.py
from clickadmin.extensions import db
from clickadmin.utils import Model
from datetime import datetime, timedelta
from flask import current_app as app
from humanize.time import naturaldelta
from sqlalchemy.schema import UniqueConstraint
from sqlalchemy import event
from sqlalchemy.orm import Session


class Experiment(Model, db.Model):

    __tablename__ = 'experiments'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Unicode(140), nullable=False, unique=True)
    description = db.Column(db.UnicodeText)
    duration = db.Column(db.Interval, nullable=False, default=timedelta(0))
    start_time = db.Column(db.DateTime)
    end_time = db.Column(db.DateTime)

    def __unicode__(self):
        return self.title

    @property
    def admin_duration(self):
        '''
        Natural representation of the duration.
        '''
        if not self.duration:
            return 'N/A'
        return naturaldelta(self.duration)

    @property
    def admin_has_valid_surveys(self):
        '''
        Whether all surveys are valid.
        '''
        return self.has_valid_surveys()

    @property
    def admin_has_valid_configurations(self):
        '''
        Whether all configurations are valid.
        '''
        return self.has_valid_configurations()

    @property
    def admin_configuration_order(self):
        '''
        String representation of ordered configurations.
        '''
        if not self.has_valid_configuration_order():
            return 'INVALID'
        return ' ~ '.join([str(c.id) for c in self.ordered_configurations])

    @property
    def ordered_configurations(self):
        '''
        Return configurations in their intended order.

        Note: This does not first check on the validity of the order.
        '''
        if not self.configurations:
            return []
        head_configuration = None
        for configuration in self.configurations:
            if not configuration.previous_configuration:
                head_configuration = configuration
        configurations = []
        current_configuration = head_configuration
        while current_configuration:
            configurations.append(current_configuration)
            current_configuration = current_configuration.next_configuration
        return configurations

    def _get_participating_users_query(self):
        from clickadmin.users import User
        start_time = self.start_time or datetime.now()
        return User.query.filter(User.created_at<start_time)

    @property
    def participating_users(self):
        '''
        Return users who were active when this experiment ran.
        '''
        return self._get_participating_users_query().all()

    @property
    def participating_users_count(self):
        '''
        Return count of users who were active when this experiment ran.
        '''
        return self._get_participating_users_query().count()

    @classmethod
    def get_experiments_in_date_range(cls, start_time, end_time, excluded=None):
        '''
        Return all experiments scheduled in a certain date range.

        @param excluded Experiment object to exclude, useful when searching for
                        other experiments in a certain date range.
        '''
        query = (cls.query
                 .filter(db.or_(cls.start_time.between(start_time, end_time),
                                cls.end_time.between(start_time, end_time))))
        if excluded:
            query = query.filter(cls.id!=excluded.id)
        return query.all()

    @classmethod
    def get_scheduled_experiments(cls):
        '''
        Return all scheduled experiments.
        '''
        return (cls.query
                .filter(cls.start_time!=None)
                .filter(cls.end_time!=None)
                .all())

    @classmethod
    def get_current_experiment(cls):
        '''
        Return any currently running experiment.
        '''
        return (cls.query
                .filter(cls.start_time<datetime.now())
                .filter(cls.end_time>datetime.now())
                .first())

    @classmethod
    def get_next_experiment(cls):
        '''
        Return the next scheduled experiment.
        '''
        return (cls.query
                .filter(cls.start_time>datetime.now())
                .order_by(cls.start_time.asc())
                .first())

    def has_valid_surveys(self):
        '''
        Check whether this experiment has valid surveys.
        '''
        for survey in self.surveys:
            if not survey.is_valid():
                return False
        return True

    def has_valid_configurations(self):
        '''
        Check whether this experiment has valid configurations.
        '''
        for configuration in self.configurations:
            if not configuration.is_valid():
                return False
        return True

    def has_valid_configuration_order(self):
        '''
        Check whether there is an ambiguity in the configuration order.
        '''
        if not self.configurations:
            return True
        head_configuration = None
        for configuration in self.configurations:
            if not configuration.previous_configuration:
                head_configuration = configuration
        if not head_configuration:
            # No head configuration
            return False
        seen_configurations = set()
        current_configuration = head_configuration
        while current_configuration:
            if current_configuration in seen_configurations:
                # Loop found
                return False
            seen_configurations.add(current_configuration)
            current_configuration = current_configuration.next_configuration
        return len(seen_configurations) == len(self.configurations)

    def is_scheduled(self):
        '''
        Check whether this experiment is scheduled.
        '''
        return self.start_time and self.end_time

    def is_past(self):
        '''
        Check whether this experiment has already run.
        '''
        return self.is_scheduled() and self.end_time < datetime.now()

    def is_current(self):
        '''
        Check whether this experiment is currently running.
        '''
        return self.is_scheduled() and self.start_time < datetime.now() < self.end_time

    def is_future(self):
        '''
        Check whether this experiment is scheduled for a future time.
        Unscheduled experiments are considered future experiments.
        '''
        if not self.is_scheduled():
            return True
        return self.start_time > datetime.now()

class Survey(Model, db.Model):

    __tablename__ = 'surveys'
    id = db.Column(db.Integer, primary_key=True)
    experiment_id = db.Column(
        db.Integer, db.ForeignKey('experiments.id', ondelete='cascade'),
        nullable=False)
    question = db.Column(db.Unicode(140), nullable=False)
    description = db.Column(db.UnicodeText)

    experiment = db.relationship(
        'Experiment', backref=db.backref('surveys'))

    def __unicode__(self):
        return self.question

    @property
    def admin_is_valid(self):
        '''
        Whether this survey is valid.
        '''
        return self.is_valid()

    @property
    def responders(self):
        '''
        Return users who responded to this survey.
        '''
        from clickadmin.users import User
        return (User.query
                .outerjoin(UserChoice, UserChoice.user_id==User.id)
                .filter(UserChoice.survey_id==self.id)
                .all())

    @property
    def responders_count(self):
        '''
        Return count of users who responded to this survey.
        '''
        return UserChoice.query.filter(UserChoice.survey_id==self.id).count()

    @property
    def nonresponders(self):
        '''
        Return users who did not respond to this survey.
        '''
        all_users = self.experiment.participating_users
        return list(set(all_users) - set(self.responders))

    @property
    def nonresponders_count(self):
        '''
        Return count of users who did not respond to this survey.
        '''
        total = self.experiment.participating_users_count
        return total - self.responders_count

    def is_valid(self):
        '''
        Surveys require at least two unique options to be valid.
        '''
        return len(self.options) > 1


class Option(Model, db.Model):

    __tablename__ = 'options'
    __table_args__ = (UniqueConstraint('survey_id', 'response'),)
    id = db.Column(db.Integer, primary_key=True)
    survey_id = db.Column(
        db.Integer, db.ForeignKey('surveys.id', ondelete='cascade'),
        nullable=False)
    response = db.Column(db.Unicode(140), nullable=False)

    survey = db.relationship(
        'Survey', backref=db.backref('options'))

    def __unicode__(self):
        return self.response

    @property
    def consenting_users(self):
        '''
        Return users who consented to this option.
        '''
        from clickadmin.users import User
        return (User.query
                .outerjoin(UserChoice, UserChoice.user_id==User.id)
                .filter(UserChoice.option_id==self.id)
                .all())

    @property
    def consenting_users_count(self):
        '''
        Return count of how many users consented to this option.
        '''
        return UserChoice.query.filter(UserChoice.option_id==self.id).count()


class Configuration(Model, db.Model):

    __tablename__ = 'configurations'
    id = db.Column(db.Integer, primary_key=True)
    previous_configuration_id = db.Column(
        db.Integer, db.ForeignKey('configurations.id'))
    experiment_id = db.Column(
        db.Integer, db.ForeignKey('experiments.id', ondelete='cascade'),
        nullable=False)
    text = db.Column(db.UnicodeText)
    duration = db.Column(db.Interval, nullable=False)

    previous_configuration = db.relationship(

clickadmin/frontend/models.py
from clickadmin.extensions import db
from clickadmin.utils import Model
from flask import abort
from sqlalchemy import event


class Page(Model, db.Model):
    '''
    Pages allow administrators to create/edit custom html pages.
    '''

    __tablename__ = 'pages'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(80), nullable=False, unique=True)
    title = db.Column(db.Unicode(255), nullable=False)
    content = db.Column(db.UnicodeText)
    permanent = db.Column(db.Boolean, nullable=False, default=False)

    def __unicode__(self):
        return self.name

    @classmethod
    def get_by_name(cls, name):
        return cls.query.filter(db.func.lower(cls.name)==db.func.lower(name)).first()

    @classmethod
    def get_by_name_or_404(cls, name):
        rv = cls.get_by_name(name)
        if rv is None:
            abort(404)
        return rv


@event.listens_for(Page, 'before_delete')
def prevent_delete(mapper, connection, target):
    if target.permanent:
        raise Exception('%s page is permanent.' % target.name.capitalize())

clickadmin/experiments/forms.py
from clickadmin.experiments.models import Option
from flask.ext.wtf import Form
from wtforms import SelectField, SubmitField
from wtforms.validators import Required


class AnswerSurveyForm(Form):
    
    option_id = SelectField('Answer', validators=[Required()], coerce=int)
    submit = SubmitField('Answer Survey')
    
    def consent_to_option(self, user):
        option = Option.get(self.option_id.data)
        user.consent_to_option(option)

clickadmin/users/forms.py
from datetime import datetime
from flask.ext.security.forms import unique_user_email
from flask.ext.wtf import Form
from wtforms import SubmitField, TextField
from wtforms.validators import Email, IPAddress, MacAddress, Required


class UpdateEmailForm(Form):
    
    email = TextField('Email', validators=[Required(), Email()])
    submit = SubmitField('Update Email')
    
    def __init__(self, current_email, *args, **kwargs):
        super(UpdateEmailForm, self).__init__(*args, **kwargs)
        self.current_email = current_email
    
    def validate_email(self, field):
        if field.data != self.current_email:
            return unique_user_email(self, field)
    
    def update_email(self, user):
        user.email = self.email.data


class UpdateHostForm(Form):
    
    ip_address = TextField('Host IP address', validators=[Required(), IPAddress(ipv4=True, ipv6=True)],
        description='IP address of machine you plan to use.')
    mac_address = TextField('Host MAC address', validators=[Required(), MacAddress()],
        description='MAC address of machine you plan to use.')
    submit = SubmitField('Update Host')
    
    def update_host(self, user):
        user.ip_address = self.ip_address.data
        user.mac_address = self.mac_address.data
        user.host_last_updated_at = datetime.now()

clickadmin/__init__.py
from clickadmin.application import create_app

clickadmin/api/__init__.py
from clickadmin.api.constants import *
from clickadmin.api.decorators import *
from clickadmin.api.forms import *
from clickadmin.api.models import *
from clickadmin.api.views import *

clickadmin/api/views.py
from flask.ext.restful import Api


def configure_api(app):
    v1 = Api(app, prefix='/api')

clickadmin/experiments/__init__.py
from clickadmin.experiments.constants import *
from clickadmin.experiments.decorators import *
from clickadmin.experiments.forms import *
from clickadmin.experiments.models import *
from clickadmin.experiments.views import *

clickadmin/experiments/views.py
from clickadmin.experiments.forms import AnswerSurveyForm
from clickadmin.experiments.models import Survey, Experiment
from flask import Blueprint, flash, redirect, render_template, url_for
from flask.ext.security import current_user, login_required


bp = Blueprint('experiments', __name__)


def index():
    experiments = Experiment.get_scheduled_experiments()
    return render_template('experiments/index.html',
                           experiments=experiments)


@bp.route('/experiment/<int:id>/')
def view_experiment(id):
    experiment = Experiment.get_or_404(id)
    return render_template('experiments/view_experiment.html',
                           experiment=experiment)


@bp.route('/experiment/<int:eid>/survey/<int:sid>/', methods=['GET', 'POST'])
@login_required
def answer_survey(eid, sid):
    experiment = Experiment.get_or_404(eid)
    return_to = url_for('.view_experiment', id=eid, _anchor='surveys')
    if not experiment.is_future():
        flash('Cannot answer experiment survey - too late.', 'warning')
        return redirect(return_to)
    survey = Survey.get_or_404(sid)
    form = AnswerSurveyForm()
    form.option_id.choices = [(o.id, o.response) for o in survey.options]
    if form.validate_on_submit():
        form.consent_to_option(current_user)
        flash('Survey answer saved successfully.', 'success')
        return redirect(return_to)
    return render_template('experiments/answer_survey.html',
                           survey=survey,
                           form=form)

clickadmin/frontend/__init__.py
from clickadmin.frontend.constants import *
from clickadmin.frontend.decorators import *
from clickadmin.frontend.forms import *
from clickadmin.frontend.models import *
from clickadmin.frontend.views import *

clickadmin/frontend/views.py
from clickadmin.frontend import Page
from flask import Blueprint, render_template


bp = Blueprint('frontend', __name__)


def index():
    return page('home')


@bp.route('/<path:name>/')
def page(name=None):
    page = Page.get_by_name_or_404(name)
    return render_template('frontend/page.html', page=page)

clickadmin/users/__init__.py
from clickadmin.users.constants import *
from clickadmin.users.decorators import *
from clickadmin.users.forms import *
from clickadmin.users.models import *
from clickadmin.users.views import *

clickadmin/users/views.py
from clickadmin.users.forms import UpdateEmailForm, UpdateHostForm
from flask import Blueprint, flash, redirect, render_template, url_for
from flask.ext.security import current_user, login_required


bp = Blueprint('users', __name__)


@bp.route('/email/', methods=['GET', 'POST'])
@login_required
def update_email():
    form = UpdateEmailForm(current_user.email, obj=current_user)
    if form.validate_on_submit():
        form.update_email(current_user)
        flash('Email updated successfully.', 'success')
        return redirect(url_for('index'))
    return render_template('users/email.html', form=form)


@bp.route('/host/', methods=['GET', 'POST'])
@login_required
def update_host():
    form = UpdateHostForm(obj=current_user)
    if form.validate_on_submit():
        form.update_host(current_user)
        flash('Host updated successfully.', 'success')
        return redirect(url_for('index'))
    return render_template('users/host.html', form=form)

clickadmin/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <base href="{{ request.host_url }}" />
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        {% block meta %}{% endblock %}
        <title>{% if title %}{{ title }} - {% endif %}Click Admin</title>
        <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" type="text/css" rel="stylesheet" />
        <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap-responsive.min.css') }}" type="text/css" rel="stylesheet" />
        <link href="{{ url_for('static', filename='css/common.css') }}" type="text/css" rel="stylesheet" />
        {% block styles %}{% endblock %}
        <script type="text/javascript">HOST_URL = {{ request.host_url|tojson }};</script>
        <script src="{{ url_for('static', filename='vendor/modernizr.min.js') }}" type="text/javascript"></script>
    </head>
    <body>
        <div id="wrapper" class="container">
            <div id="header" class="navbar navbar-inverse navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <span class="brand">Click Admin</span>
                        <div class="nav-collapse collapse">
                            <ul class="nav">
                                <li><a href="{{ url_for('index') }}">Home</a></li>
                            </ul>
                            <ul class="nav pull-right">
                                {% if current_user.is_authenticated() %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        {{ current_user.email }}
                                        -
                                        {{ current_user.ip_address or 'no ip address' }}
                                        -
                                        {{ current_user.mac_address or 'no mac address' }}
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{{ url_for('users.update_host') }}">Change Host</a></li>
                                        <li><a href="{{ url_for('users.update_email') }}">Change Email</a></li>
                                        <li><a href="{{ url_for_security('change_password') }}">Change Password</a></li>
                                        <li class="divider"></li>
                                        <li><a href="{{ url_for('security.logout') }}">Log Out</a></li>
                                        {% if current_user.has_role('admin') %}
                                            <li class="divider"></li>
                                            <li><a href="{{ url_for('admin.index') }}">Admin Section</a></li>
                                        {% endif %}
                                    </ul>
                                </li>
                                {% else %}
                                <li><a href="{{ url_for('security.login') }}">Log In</a></li>
                                <li><a href="{{ url_for('security.register') }}">Register</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
	        <div id="body">
                {% with messages = get_flashed_messages(with_categories=True) %}
			        {% if messages %}
			            {% for category, m in messages %}
			                <div class="alert alert-block alert-{{ category }}">
                                <a href="javascript:void(0)" class="close" data-dismiss="alert">x</a>
			                    {{ m }}
			                </div>
			            {% endfor %}
			        {% endif %}
			    {% endwith %}
                {% block body %}{% endblock %}
            </div>
            <div id="push"><!--//--></div>
        </div>
        {% include 'includes/footer.html' %}
        <script src="{{ url_for('static', filename='vendor/jquery.min.js') }}" type="text/javascript"></script>
        <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
        <script src="{{ url_for('static', filename='js/common.js') }}" type="text/javascript"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

clickadmin/templates/macros.html
{% macro control_group(field) %}
    {% set description_parts = [field.label.text, field.description] if field.description else [field.label.text] %}
    <div class="control-group {{ 'error' if field.errors }}" title="{{ ' - '.join(description_parts) }}">
        {{ field.label(class='control-label') }}
        <div class="controls">
            {{ field(**kwargs)|safe }}
            {% if field.errors %}
                <span class="help-block">{{ field.errors.pop() }}</span>
            {% endif %}
        </div>
    </div>
{% endmacro %}

{% macro control_group_button(button) %}
    <div class="control-group">
        <div class="controls">
            {{ button(class_='btn btn-primary') }}
        </div>
    </div>
{% endmacro %}

{% macro calendar(experiments, url_endpoint=None, default_view='month') %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#calendar').fullCalendar({
                theme: true,
                allDayDefault: false,
                allDaySlot: false,
                slotMinutes: 60,
                defaultView: {{ default_view|tojson|safe }},

                header: {
                    left: 'month,agendaWeek,agendaDay',
                    center: 'title',
                    right: 'today prev,next'
                },

                titleFormat: {
                    month: 'MMMM yyyy',
                    week: 'MMM d[ yyyy]{ - [ MMM] d yyyy}',
                    day: 'MMM d, yyyy'
                },

                eventMouseover: function (event, jsEvent, view) {
                	var classes = $(this).attr('class');
                	var parts = classes.match(/(past|future|current)/);
                	$(this).attr('title', parts[0] + ' experiment');
                },

                events: [
                {% for experiment in experiments %}
                    {
                        id: {{ experiment.id }},
                        title: {{ experiment.title|tojson|safe }},
                        start: {{ experiment.start_time|datetimeformat|tojson|safe }},
                        end: {{ experiment.end_time|datetimeformat|tojson|safe }},
                        {% if url_endpoint %}
                        url: {{ url_for(url_endpoint, id=experiment.id)|tojson|safe }},
                        {% endif %}
                        className: {{ ('past' if experiment.is_past() else 'future' if experiment.is_future() else 'current')|tojson|safe }}
                    }{{ ',' if not loop.last }}
                {% endfor %}
                ]
            });
        });
    </script>
{% endmacro %}

{% macro calendar_styles() %}
    <link href="{{ url_for('static', filename='vendor/fullcalendar/cupertino/theme.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ url_for('static', filename='vendor/fullcalendar/fullcalendar.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ url_for('static', filename='vendor/fullcalendar/fullcalendar.print.css') }}" type="text/css" rel="stylesheet" />
{% endmacro %}

{% macro calendar_scripts() %}
    <script src="{{ url_for('static', filename='vendor/fullcalendar/fullcalendar.min.js') }}" type="text/javascript"></script>
{% endmacro %}

{% macro chart(survey) %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#survey-{{ survey.id }} .chart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false
                },
                title: {
                    text: {{ survey.question|tojson|safe }}
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            color: '#000000',
                            connectorColor: '#000000',
                            format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                        }
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Number of users',
                    data: [
                    {% for option in survey.options %}
                        [
                            {{ option.response|tojson|safe }},
                            {{ option.consenting_users_count }}
                        ]{{ ',' if not loop.last }}
                    {% endfor %}
                    ]
                }]
            });
            $('#survey-{{ survey.id }} .open').click(function() {
                $('#survey-{{ survey.id }} .chart').slideToggle('slow');
            });
            $('#survey-{{ survey.id }} .chart').hide();
        });
    </script>
{% endmacro %}

{% macro chart_scripts() %}
    <script src="{{ url_for('static', filename='vendor/highcharts/js/highcharts.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='vendor/highcharts/js/modules/exporting.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='vendor/highcharts/js/themes/grid.js') }}" type="text/javascript"></script>
{% endmacro %}